services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'  # Map the container's port 3000 to the host
    volumes:
      - .:/usr/client  # Mount the local directory as a volume to reflect code changes
    env_file:
      - .env
    networks:
      - youtube_share

networks:
  youtube_share:
    driver: bridge